"use client";
import Navbar from "@/components/NavBar/Navbar";
import "./globals.css";
import { usePathname } from "next/navigation";
import { UserProvider } from "@/context/UserContext";
import { useIsMobile } from "@/hooks/useIsMobile";

// export const metadata = {
//   title: "EvHomes",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const isMobile = useIsMobile();

  const paddingTop = pathname === "/" ? 0 :isMobile ? 30 : 60;

  return (
    <html lang="en">
      <body
        className="container"
        style={{ paddingTop }}
      >
        <UserProvider>
          <Navbar />
          {children}
        </UserProvider>

        {/* {children} */}
      </body>
    </html>
  );
}
