// app/layout.tsx
import "./globals.css";
import { Providers } from "./providers";
import AppLayout from "@/components/AppLayout";

export const metadata = {
  title: "EvHomes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AppLayout>{children}</AppLayout>
        </Providers>
      </body>
    </html>
  );
}
